language: python
dist: xenial
python:
  - "2.7"
  - "3.7"

sudo: false

notifications:
  email: false
 
# Setup dependencies and install package
install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # There is a (temporary?) issue with conda-forge build that requires proj4
  # https://github.com/conda-forge/basemap-feedstock/issues/30
  - conda create -q -n travis-env python=$TRAVIS_PYTHON_VERSION setuptools numpy scipy matplotlib basemap astropy ephem healpy pandas nose -c conda-forge
  - source activate travis-env
  - python setup.py install

before_script:
  - export MPLBACKEND=Agg
  - conda install -q ipython notebook -c conda-forge --no-update-deps

# command to run tests
script: 
  - python -c "import skymap; print(skymap.__version__)"
  - if [[ $TRAVIS_PYTHON_VERSION < 3.0 ]]; then
      nosetests ;
    else 
      nosetests -I test_tutorial.py ;
    fi
